name: CI_tests
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    # Setup FVM
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      with:
        path: 'wellbeing-mapper-app'
        
    - name: Setup Flutter via FVM
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: 'wellbeing-mapper-app/.fvmrc'
        channel: 'stable'
        cache: true
         
    - name: Get flutter dependencies
      run: |
        cd wellbeing-mapper-app
        flutter pub get
    
    - name: Statically analyze the Dart code for any errors.
      run: |
        cd wellbeing-mapper-app
        flutter analyze
    
    - name: Run tests for our flutter project.
      run: |
        cd wellbeing-mapper-app
        flutter test
      working-directory: wellbeing-mapper-app
      
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: wellbeing-mapper-app/coverage/lcov.info
