name: integration_test Android

# Only run on manual trigger or main branch pushes to reduce CI load
on: 
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

# A workflow run is made up of one or more jobs.
jobs:

  integration_android:
    # The type of machine to run the job on.
    runs-on: macos-13 # Use specific macOS version for better consistency
    timeout-minutes: 45
    continue-on-error: true # Don't fail the workflow if this job fails
    # creates a build matrix for your jobs
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      # set of different configurations of the virtual environment.
      matrix:
        api-level: [29]
        target: [google_apis]
    steps:
      - uses: actions/checkout@v4
      
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/local/lib/android/sdk/build-tools/*/renderscript
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/node_modules
          df -h
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true
          
      - name: Get Flutter dependencies
        run: |
          cd wellbeing-mapper-app
          flutter pub get
          
      - name: Run Flutter Doctor
        run: |
          cd wellbeing-mapper-app
          flutter doctor -v
        
      - name: "Run Integration tests"
        # Use a simpler, more reliable emulator configuration
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          emulator-boot-timeout: 1800 # 30 minutes
          script: |
            cd wellbeing-mapper-app
            echo "Starting integration tests..."
            timeout 600 flutter test integration_test/app_test.dart || echo "Test completed or timed out"
